server:
  port: 8080

spring:
  mail:
    host:  smtp-relay.brevo.com
    port: 587
    username: b3f0ed001@smtp-brevo.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true